### ISSUE TITLE
Files moved improperly

### ISSUE THREAD

**Issue by giozucca** [riolubruh/SplitLargeFiles#2]
Downloading files using the plugin after being parsed leaves the file unreadable. Tried this with an .mp4 file and a .wav file, and both downloaded being bigger than they were originally and failed to play in their respective players (VLC and MPC). However, downloading the 2 split files (these files only needed to be split into 2 parts) separate and then using the repo to combine them worked as intended.

**Comment by riolubruh** [comment]
Found the problem. The file is correctly assembled in %tmp%, but then the save dialog downloads all of the files as one (and then the plugin deletes the directory in %tmp%). A fix is coming soon.

**Comment by giozucca** [comment]
The plugin states it will save the file to the desktop, however, it doesn't seem to actually download anything (maybe it's simply not moving the file properly). After downloading I cannot find the file in any directory. (Also I think the default download directory should be the downloads folder for simplicity)

**Comment by riolubruh** [comment]
Hmm. It worked for me on Windows 10. Open console and type process.env.USERPROFILE and see what it outputs.
I didn't test it on any other OSes or PCs so it could be related to that, or possibly not.

**Comment by riolubruh** [comment]
Okay, new plan of action:
Instead of moving the file, we're just gonna open the folder. It's not the cleanest solution, but it should hopefully work.

**Comment by riolubruh** [comment]
056a97eeafc91ead27d34272d1dec68e1c13936c
