### ISSUE TITLE
Option for split size

### ISSUE THREAD

**Issue by riolubruh** [riolubruh/SplitLargeFiles#3]
I'm planning on adding an option in the settings menu to manually choose the split size, default being 8MB, and then options for 50MB, 100MB, and 500MB respectively.

**Comment by Cxsmo-ai** [comment]
the split file is showing as multiple files instead of one

**Comment by riolubruh** [comment]
> the split file is showing as multiple files instead of one

I cannot reproduce this. 

![image](https://user-images.githubusercontent.com/54255074/228645071-8291c3ba-b078-4d08-a663-f8567d39abed.png)
Make sure you are on the very latest versions of the plugin and BetterDiscord.

**Comment by Cxsmo-ai** [comment]
It just keeps show up as only a bunch of dlfc files not one file and I was trying it on a over 100mb file

**Comment by Cxsmo-ai** [comment]
![image](https://user-images.githubusercontent.com/74084396/228727888-a27b0cb3-bcdf-4c05-a1ac-59701ccac989.png)

**Comment by Finny7667** [comment]
Same thing for me on a 60mb video file
![image](https://user-images.githubusercontent.com/35304446/230019709-6f92e44b-3cc9-4e79-b4a1-f87c608b2643.png)

**Comment by theleanbow** [comment]
same issue here as well
does this require both sender and receiver to have the same plugin perhaps?
if so, then maybe need to update readme?

this is how it shows in my device
![image](https://user-images.githubusercontent.com/66841515/230647263-28119edc-f108-40d0-91f7-cc64944722c2.png)

this is how it shows in everyone else's device
![image](https://user-images.githubusercontent.com/66841515/230647177-c22a92d4-ef51-4b13-89d5-24ec1b809be3.png)

**Comment by riolubruh** [comment]
**Both the sender and the recipient need to have the plugin** in order for it to render in the nice-looking way (which from now on I'll refer to as a "downloadable").
Additionally, sometimes the plugin doesn't initially refresh the downloadables correctly on a page due to the page taking too long to load. If that happens, then switching channels should refresh the downloadables on that page correctly.

**Comment by riolubruh** [comment]
Also there is currently a newer bug that sometimes prevents attachments from rendering correctly which I'm working on a fix for right now
