### ISSUE TITLE
fix load error after recent discord update

### ISSUE THREAD

**Issue by ffuentesm** [riolubruh/SplitLargeFiles#9]
Just want to know an ETA on an update to fix the crash due to the new update, since this plugin in not on the BD main plugging page I never know when it will update. 
![image](https://github.com/riolubruh/SplitLargeFiles/assets/44974827/7f11119a-0d1d-4eb5-b65c-f96e348cb93d)

**Comment by riolubruh** [comment]
I don't have an ETA for you just yet, as I haven't had a chance to look into how much was actually broken with the update, as I've been working on YABDP4Nitro changes and fixes instead.

**Comment by riolubruh** [comment]
fixed
